plugins/Users/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

Router::plugin(
    'Users',
    ['path' => '/users'],
    function (RouteBuilder $routes) {
        $routes->fallbacks('DashedRoute');
    }
);

plugins/Users/src/Model/Entity/User.php
<?php
namespace Users\Model\Entity;

use Cake\Auth\DefaultPasswordHasher;
use Cake\ORM\Entity;

/**
 * User Entity
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property bool $role
 * @property \Cake\I18n\Time $created
 * @property string $token_password
 * @property int $status
 * @property int $user_info_id
 *
 * @property \Users\Model\Entity\UserInfo $user_info
 */
class User extends Entity{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    protected function _setPassword($value){
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($value);
    }
    
    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];
}

plugins/Users/src/Model/Entity/Userinfo.php
<?php
namespace Users\Model\Entity;

use Cake\ORM\Entity;

/**
 * UserInfo Entity
 *
 * @property int $id
 * @property string $rut
 * @property string $name
 * @property string $lastname
 * @property string $address
 * @property string $tel_phone
 * @property string $tel_cellphone
 *
 * @property \Users\Model\Entity\User[] $users
 */
class Userinfo extends Entity{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
    
    protected function _getFullName(){
        return $this->_properties['name'] . '  ' .$this->_properties['lastname'];
    }
}

plugins/Users/src/Model/Table/UsersTable.php
<?php
namespace Users\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \Cake\ORM\Association\BelongsTo $UserInfos
 *
 * @method \Users\Model\Entity\User get($primaryKey, $options = [])
 * @method \Users\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \Users\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \Users\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Users\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Users\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \Users\Model\Entity\User findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table{
    
    public $_roles = [
        0 => 'Usuario',
        1 => 'Administrador'
    ];
    
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config){
        parent::initialize($config);

        $this->table('users');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->addBehavior('Log',[
            'plugin' => 'Users',
            'useTable' => 'UserLogs',
            'messageCreate' => __('Se ha creado un nuevo usuario.'),
            'messageUpdate' => __('Se ha modificado un usuario.'),
            'messageDelete' => __('Se ha eliminado un usuario')
        ]);
        $this->HasOne('Userinfos', [
            'bindingKey' => 'userinfo_id',
            'foreignKey' => 'id',
            'className' => 'Users.Userinfos',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator){
        
        $validator
            ->requirePresence('username', 'true')
            ->notEmpty('username','Debe escribir un nombre de usuario.')
            ->add('username',[
                'unique' => [
                    'rule' => 'validateUnique',
                    'provider' => 'table',
                    'message' => 'Nombre de usuario ya registrado.'
                ]
            ]);

        $validator
            ->requirePresence('password','true')
            ->notEmpty('password','Debe escribir una contraseña.')
            ->add('password', [
                'compare' => [
                    'rule' => ['compareWith', 'confirm_password'],
                    'message' => 'Las contraseñas no coinciden.'
                ]
            ]);

        $validator
            ->requirePresence('email', 'true')
            ->notEmpty('email','Debe escribir su correo electrónico.')
            ->add('email',[
                'valid-email' => [
                    'rule' => 'email',
                    'message' => 'Formato de email inválido.'
                ],
                'unique' => [
                    'rule' => 'validateUnique',
                    'provider' => 'table',
                    'message' => 'Email ya registrado.'
                ]
            ]);

        $validator
            ->requirePresence('role', 'create')
            ->notEmpty('role', 'Debe escoger un rol de usuario');

        $validator
            ->allowEmpty('token_password');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules){
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->isUnique(['email']));

        return $rules;
    }
    
    public function validationUpdatePassword(Validator $validator ){
        $validator
            ->add('password', [
                'length' => [
                    'rule' => ['minLength', 6],
                    'message' => 'La contraseña debe contener por lo menos 6 caracteres.',
                ],
                'match' => [
                    'rule' => ['compareWith','confirm_password'],
                    'message' => 'Las contraseñas no coinciden.',
                ]
            ])
            ->notEmpty('password');
 
        return $validator;
    }
}

plugins/Users/src/Controller/UsersController.php
<?php
namespace Users\Controller;

use Users\Controller\AppController;
use Cake\Mailer\Email;
use Cake\Utility\Hash;

/**
 * Users Controller
 *
 * @property \Users\Model\Table\UsersTable $Users
 */
class UsersController extends AppController{

    public function initialize(){
        parent::initialize();
        $this->loadComponent('Paginator');
        $this->Auth->allow([
            'adminRequestNewPassword',
            'adminChangePassword',
            'adminAdd'
        ]);
    }
    
    /**
     * Login method
     *
     * @return \Cake\Network\Response|null
     */
    public function login(){
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                if($this->Auth->user('is_admin') == 1){
                    return $this->redirect(['action' => 'adminDashboard']);
                }
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Nombre de usuario o contraseña incorrectos.'));
        }
    }
    
    /**
     * Logout method
     *
     * @return \Cake\Network\Response|null Redirects to index.
     */
    public function logout(){
        $this->Flash->success('Te haz desconectado.');
        return $this->redirect($this->Auth->logout());
    }
    
    public function register(){
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
            }
        }
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }
    
    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function adminIndex(){
        $this->paginate = [
            'contain' => ['Userinfos']
        ];
        $users = $this->paginate($this->Users);
        
        $this->set('roles', $this->Users->_roles);
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }
    
    /**
     * admin_dashboard method
     * Mostramos el dashboard del usuario administrador, con los logs correspondientes.
     *
     * @return \Cake\Network\Response|null
     */
    public function adminDashboard(){
        $logsTable = parent::getTableInstance('Logs');
        $userLogsTable = parent::getTableInstance('Users.UserLogs');
        
        if($this->request->is('post')){
            switch($this->request->data['actions']):
                case 1:
                case 3:
                    if(isset($this->request->data['chk'])):
                        $selected = Hash::extract($this->request->data['chk'],'{n}.id');
                        if($this->request->data['actions'] == 1):
                            $query = $userLogsTable->find('all',['conditions' => ['UserLogs.id IN' => $selected]])->toArray();
                            foreach($query as $row):
                                $row->status = 1;
                                $userLogsTable->save($row);
                            endforeach;
                            $this->Flash->success(__('Registros guardados como leídos.'));
                        else:
                            $userLogsTable->deleteAll(['id IN' => $selected]);
                            $this->Flash->success(__('Registro(s) eliminado(s).'));
                        endif;
                    else:
                        $this->Flash->error(__('Debe escoger por lo menos un registro.'));
                    endif;
                break;
                case 2:
                case 4:
                    if($this->request->data['actions'] == 2):
                        $entities = $userLogsTable->find('all');
                        foreach($entities as $entity):
                            $entity->status = 1;
                            $userLogsTable->save($entity);
                        endforeach;
                        $this->Flash->success(__('Registros guardados como leídos.'));
                    else:
                        $entities = $userLogsTable->find('list',[
                            'keyField' => 'id',
                            'valueField' => 'id'
                        ])->toArray();
                        $userLogsTable->deleteAll(['id IN' => $entities]);
                        $this->Flash->success(__('Registros eliminados.'));
                    endif;
                break;
                default:
                    $this->Flash->error(__('Debe escoger una opción válida.'));
                break;
            endswitch;
            $this->request->data = array();
        }
        $logs = $logsTable->find('all');
        $cantNewUsers = $userLogsTable->find('all',['conditions' => ['action' => 'create']])->count();
        
        $users = $this->Users->find('list',[
            'keyField' => 'id',
            'valueField' => 'username'
        ])->toArray();
        
        $this->set(compact('logs','cantNewUsers','users'));
        $this->set('_serialize', ['logs','userLogs']);
    }

    /**
     * Método para < Mis Datos
     *
     * Associated Route: /mis-datos
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException Cuando la entidad no fue encontrada
     */
    public function profile(){
        # obtenemos la entidad del usuario logueado junto a su información.
        $id = $this->Auth->user('id');
        $user = $this->Users->get($id,['contain'=>['Userinfos']]);
        # si el parámetro "edit" en la ruta es true significa que editará sus datos
        if($this->request->params['edit']):
            # dejamos sin valor la contraseña para que la escriba nuevamente (sólo por seguridad)
            unset($user->password);
            if ($this->request->is(['patch', 'post', 'put'])) {
                $user = $this->Users->patchEntity($user, $this->request->data);
                if($this->Users->hasBehavior('Log')){
                    $this->Users->setUserToLog($this->Auth->user('id'));
                }
                if ($this->Users->save($user)) {
                    $this->Flash->success(__('El usuario ha sido guardado.'));
    
                    return $this->redirect(['action' => 'profile', 'edit' => false]);
                } else {
                    $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
                    unset($user->password);
                    unset($user->confirm_password);
                }
            }
            $this->set('roles',$this->Users->_roles);
            $this->set('edit',true);
        endif;
        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function adminAdd(){
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data,[
                'associated' => [
                    'Userinfos'
                ]
            ]);
            if($this->Users->hasBehavior('Log')){
                $this->Users->setUserToLog($this->Auth->user('id'));
            }
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));
                return $this->redirect(['action' => 'adminIndex']);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
            }
        }
        $this->set('roles',$this->Users->_roles);
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function adminEdit($id = null){
        $user = $this->Users->get($id, [
            'contain' => ['Userinfos']
        ]);
        unset($user->password);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if($this->Users->hasBehavior('Log')){
                $this->Users->setUserToLog($this->Auth->user('id'));
            }
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));

                return $this->redirect(['action' => 'adminIndex']);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
                unset($user->password);
                unset($user->confirm_password);
            }
        }
        $this->set('roles',$this->Users->_roles);
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function adminDelete($id = null){
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if($this->Users->hasBehavior('Log')){
            $this->Users->setUserToLog($this->Auth->user('id'));
        }
        if ($this->Users->delete($user)) {

plugins/Users/src/Template/Users/admin_change_password.ctp
<div class="login-box-body">
    <?= $this->Flash->render();?>
    <p class="login-box-msg"><?=__('Cambiar contraseña.');?></p>
    <?php
        echo $this->Form->create($user,[
            'novalidate' => true,
            'templates' => [
                'inputContainer' => '
                <div class="form-group has-feedback {{errorClass}}">
                    {{content}}
                    <span class="glyphicon {{icoClass}} form-control-feedback"></span>
                    {{errorMessage}}
                </div>'
            ]
        ]);
        
        echo $this->Form->input('password',[
                'placeholder' => __('Nueva Contraseña'),
                'label' => false,
                'class' => 'form-control',
                'div' => false,
                'templateVars' => [
                    'icoClass' => 'glyphicon-lock',
                    'errorClass' => ($this->Form->isFieldError('password') ? 'has-error' : ''),
                    'errorMessage' => $this->Form->error('password')
                ],
                'error' => false
        ]);
        
        echo $this->Form->input('confirm_password',[
                'placeholder' => __('Confirmar Contraseña'),
                'label' => false,
                'div' => false,
                'type' => 'password',
                'class' => 'form-control',
                'templateVars' => [
                    'icoClass' => 'glyphicon-lock'
                ],
                'error' => false
        ]);
    ?>
        <div class="row">
            <div class="col-xs-12">
                <?=$this->Form->submit('Guardar',[
                        'class' => 'btn btn-primary btn-block btn-flat pull-right',
                        'style' => 'width:40%;',
                        'div' => false
                ]);?>
            </div>
        </div>
    <?=$this->Form->end();?>
</div>

plugins/Users/src/Template/Users/admin_dashboard.ctp
<?php $this->assign('title', 'FIE | Dashboard'); ?>
<?php echo $this->Html->script('Users.admin_get_log_list'); ?>
<section class="content-header">
    <h1>Dashboard</h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i>
            <?=$this->Html->link('Home',['action' => 'adminDashboard'],['title' => 'Ir a','escape' => false]);?>
        </li>
        <li class="active">
            Dashboard
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3><?=$cantNewUsers;?></h3>
                    <p><?=__('Nuevos usuarios');?></p>
                </div>
                <div class="icon"><i class="ion ion-person-add"></i></div>
                <?=$this->Html->link('Más información <i class="fa fa-arrow-circle-right"></i>','',['class' => 'small-box-footer', 'escape' => false]);?>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>22</h3>
                    <p><?=__('Nuevas postulaciones');?></p>
                </div>
                <div class="icon"><i class="ion ion-ios-paper"></i></div>
                <?=$this->Html->link('Más información <i class="fa fa-arrow-circle-right"></i>','',['class' => 'small-box-footer', 'escape' => false]);?>
            </div>
        </div>
    </div>
    <div class="box box-primary">
        <div class="box-header">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title"><?=__('Registros de Usuarios');?></h3>
        </div>
        <?=$this->Form->create('Filter',['novalidate' => true, 'id' => 'AdminDashboardForm']);?>
        <div class="box-body">
            <?=$this->Flash->render();?>
                <div class="form-group col-lg-4">
                    <label><?=__('Mostrar:');?></label>
                    <?=$this->Form->select('show',[
                        __('Mostrar no leídos'),
                        __('Sólo creaciones'),
                        __('Sólo modificaciones'),
                        __('Sólo eliminaciones'),
                        __('Mostrar leídos')
                    ],[
                        'class' => 'form-control',
                        'id' => 'AdminDashboardShow'
                    ]);?>
                </div>
                <div class="form-group col-lg-4">
                    <label><?=__('Ordenar:');?></label>
                    <?=$this->Form->select('order',[
                        __('Más recientes primero'),
                        __('Más antiguos primero')
                    ],[
                        'class' => 'form-control',
                        'id' => 'AdminDashboardOrder'
                    ]);?>
                </div>
                <div class="form-group col-lg-4">
                    <label><?=__('Autor:');?></label>
                    <?=$this->Form->select('autor',$users,[
                        'class' => 'form-control',
                        'empty' => 'Seleccione...',
                        'id' => 'AdminDashboardAutor'
                    ]);?>
                </div>
            
            <div class="logs-users-list" style="height: 400px; max-height: 400px;border: 2px solid #E6E7E8; display: flex;"></div>
            <div class="form-group col-lg-3">
                <label><?=__('Acciones para seleccionados:');?></label>
                <?=$this->Form->select('actions',[
                    1 => __('Marcar como leídos (Seleccionados)'),
                    2 => __('Marcar como leídos (Todos)'),
                    3 => __('Eliminar (Seleccionados)'),
                    4 => __('Eliminar (Todos)')
                ],[
                    'empty' => __('Seleccione...'),
                    'class' => 'form-control',
                    'id' => 'AdminDashboardActions'
                ]);?>
            </div>
        </div>
        <?=$this->Form->end();?>
    </div>
</section>

plugins/Users/src/Template/Users/admin_index.ctp
<?php $this->assign('title', 'FIE | Usuarios'); ?>
<section class="content-header">
    <h1 class="page-header"><?=__('Usuarios');?></h2>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i>
            <?=$this->Html->link(__('Dashboard'),['action' => 'adminDashboard']);?>
        </li>
        <li class="active">
            <i class="fa fa-users"></i> <?=__('Usuarios');?>
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <?=$this->Flash->render();?>
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"><?=__('Listado Usuarios Registrados');?></h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <style type="text/css">
                                thead th { color: #3c8dbc; }
                            </style>
                            <table class="table table-bordered table-hover dataTable">
                                <thead>
                                    <th><?= $this->Paginator->sort('id',__('ID')) ?></th>
                                    <th><?= $this->Paginator->sort('userinfo.rut',__('Rut')) ?></th>
                                    <th><?= $this->Paginator->sort('username',__('Username')) ?></th>
                                    <th><?= $this->Paginator->sort('email',__('Email')) ?></th>
                                    <th><?= __('Nombre Completo') ?></th>
                                    <th><?= __('Rol')?></th>
                                    <th><?= $this->Paginator->sort('active',__('Estado')) ?></th>
                                    <th class="actions text-center"><?= __('Acciones') ?></th>
                                </thead>
                                <tbody>
                                    <?php foreach ($users as $user): ?>
                                    <tr>
                                        <td><?= $this->Number->format($user->id) ?></td>
                                        <td><?= $user->userinfo->rut ?></td>
                                        <td><?= $user->username ?></td>
                                        <td><?= $user->email ?></td>
                                        <td><?= $user->userinfo->full_name ?></td>
                                        <td><?= $roles[$user->is_admin]; ?></td>
                                        <td><?= $user->active == 1 ? 'Habilitado' : 'Deshabilitado' ?></td>
                                        <td class="actions" style="width: 10%;">
                                            <?= $this->Html->link('<i class="fa fa-edit" aria-hidden="true"></i>',
                                                        ['action' => 'adminEdit', $user->id],
                                                        ['escape' => false,'title' => 'Editar']);
                                            ?>
                                            <?= $this->Html->link('<i class="fa fa-refresh" aria-hidden="true"></i>',
                                                        ['action' => 'adminChangeStatus', $user->id],
                                                        ['escape' => false,'title' => 'Cambiar estado']);
                                            ?>
                                            <?= $this->Form->postLink('<i class="fa fa-trash" aria-hidden="true"></i>',
                                                        ['action' => 'adminDelete', $user->id],
                                                        ['escape' => false, 'title' => 'Eliminar',
                                                         'class' => 'pull-right',
                                                         'confirm' => __('¿Estás seguro de querer eliminar al usuario ID # {0}?', $user->id)]);
                                            ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <ul class="pagination">
                                <?= $this->Paginator->prev('< ' . __('Anterior')) ?>
                                <?= $this->Paginator->numbers() ?>
                                <?= $this->Paginator->next(__('Siguiente') . ' >') ?>
                            </ul>
                            <p><?= $this->Paginator->counter() ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

plugins/Users/src/Template/Users/admin_request_new_password.ctp
<div class="login-box-body">
    <?= $this->Flash->render();?>
    <p class="login-box-msg">
        <?=__('Por favor, introduzca el correo electrónico que utilizó para su registro,
              donde se le enviarán instrucciones para finalizar el proceso de
              recuperación de contraseña.');
        ?>
    </p>
    <?php
        echo $this->Form->create('',[
            'novalidate' => false,
            'templates' => [
                'inputContainer' => '
                <div class="form-group has-feedback">
                    {{content}}
                    <span class="glyphicon {{icoClass}} form-control-feedback"></span>
                </div>'
            ]
        ]);
        
        echo $this->Form->input('email',[
                'placeholder' => __('Email'),
                'label' => false,
                'class' => 'form-control',
                'templateVars' => [
                    'icoClass' => 'glyphicon-envelope'
                ]
        ]);
    ?>
        <div class="row">
            <div class="col-xs-12">
                <?=$this->Form->submit('Enviar',[
                        'class' => 'btn btn-primary btn-block btn-flat pull-right',
                        'style' => 'width:40%;',
                        'div' => false
                ]);?>
            </div>
        </div>
        <div class="row" style="margin: 0;">
            <?=$this->Html->link(__('< Volver'),'/admin/login');?><br />
        </div>
    <?=$this->Form->end();?>
</div>

plugins/Users/src/Template/Users/profile.ctp
<? if(!isset($edit)): ?>
    <?=__('Mis datos');?><br />
    <?=__('Nombre:');?><?=$user->userinfo->full_name;?><br />
    <?=__('Dirección:');?><?=$user->userinfo->address;?><br />
    <?=__('Teléfono:');?><?=$user->userinfo->tel_cellphone;?><br />
    <?=__('email:');?><?=$user->email;?><br />
    <?=$this->Html->link(__('Editar'),['controller' => 'Users', 'action' => 'profile', 'edit' => true]);?>
<? else: ?>

<?=$this->Form->create($user);?>
    <?=$this->Form->hidden('id');?>
    <?=$this->Form->input('username');?>
    <?=$this->Form->input('password');?>
    <?=$this->Form->input('confirm_password',['type' => 'password']);?>
    <?=$this->Form->input('email');?>
    <?=$this->Form->input('userinfo.rut');?>
    <?=$this->Form->input('userinfo.name');?>
    <?=$this->Form->input('userinfo.lastname');?>
    <?=$this->Form->input('userinfo.address');?>
    <?=$this->Form->input('userinfo.tel_phone');?>
    <?=$this->Form->input('userinfo.tel_cellphone');?>
    <?=$this->Form->submit('Guardar');?>
<?=$this->Form->end();?>

<? endif; ?>