config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Projects' in plugin 'Projects',
     * its action called 'index', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['plugin' => 'Projects','controller' => 'Projects', 'action' => 'index']);
    
    $routes->connect('/login',['plugin' => 'Users', 'controller' => 'Users', 'action' => 'login']);
    $routes->connect('/logout',['plugin' => 'Users', 'controller' => 'Users', 'action' => 'logout']);
    
    /**
     * Aquí hacemos las rutas hacia el plugin de usuarios.
     */
    $routes->connect('/users/users/:action',['plugin' => 'Users', 'controller' => 'Users']);
    $routes->connect('/users/users/:action/*',['plugin' => 'Users', 'controller' => 'Users']);
    
    $routes->connect('/mis-datos', ['plugin' => 'Users','controller' => 'Users', 'action' => 'profile', 'edit' => false]);
    $routes->connect('/mis-datos/editar', ['plugin' => 'Users','controller' => 'Users', 'action' => 'profile', 'edit' => true]);
    
    
    /**
     * Aquí hacemos las rutas hacia el plugin de proyectos
     */
    $routes->connect('/postular/paso-1',['plugin' => 'Projects', 'controller' => 'Projects', 'action' => 'step_one']);
    $routes->connect('/postular/paso-2',['plugin' => 'Projects', 'controller' => 'Projects', 'action' => 'step_two']);
    $routes->connect('/postular/paso-3',['plugin' => 'Projects', 'controller' => 'Projects', 'action' => 'step_three']);
    $routes->connect('/postular/paso-4',['plugin' => 'Projects', 'controller' => 'Projects', 'action' => 'step_four']);
    
    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/School.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * School Entity
 *
 * @property int $id
 * @property int $institution_region_id
 * @property int $institution_province_id
 * @property int $institution_district_id
 * @property string $name
 * @property string $rbd
 * @property string $dependence
 * @property string $sostenedor
 * @property string $geographical_area
 * @property string $ive_sinae
 * @property bool $visible
 *
 * @property \App\Model\Entity\InstitutionRegion $institution_region
 * @property \App\Model\Entity\InstitutionProvince $institution_province
 * @property \App\Model\Entity\InstitutionDistrict $institution_district
 * @property \App\Model\Entity\Project[] $projects
 */
class School extends Entity{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Table/SchoolsTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Schools Model
 *
 * @property \Cake\ORM\Association\BelongsTo $InstitutionRegions
 * @property \Cake\ORM\Association\BelongsTo $InstitutionProvinces
 * @property \Cake\ORM\Association\BelongsTo $InstitutionDistricts
 * @property \Cake\ORM\Association\HasMany $Projects
 *
 * @method \App\Model\Entity\School get($primaryKey, $options = [])
 * @method \App\Model\Entity\School newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\School[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\School|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\School patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\School[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\School findOrCreate($search, callable $callback = null)
 */
class SchoolsTable extends Table{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config){
        parent::initialize($config);

        $this->table('schools');
        $this->displayField('name');
        $this->primaryKey('id');

        $this->belongsTo('Regions', [
            'foreignKey' => 'region_id'
        ]);
        $this->belongsTo('Provinces', [
            'foreignKey' => 'province_id'
        ]);
        $this->belongsTo('Districts', [
            'foreignKey' => 'district_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Projects', [
            'foreignKey' => 'school_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator){
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('name');

        $validator
            ->allowEmpty('rbd');

        $validator
            ->requirePresence('dependence', 'create')
            ->notEmpty('dependence');

        $validator
            ->requirePresence('sostenedor', 'create')
            ->notEmpty('sostenedor');

        $validator
            ->requirePresence('geographical_area', 'create')
            ->notEmpty('geographical_area');

        $validator
            ->allowEmpty('ive_sinae');

        $validator
            ->boolean('visible')
            ->requirePresence('visible', 'create')
            ->notEmpty('visible');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules){
        $rules->add($rules->existsIn(['region_id'], 'Regions'));
        $rules->add($rules->existsIn(['province_id'], 'Provinces'));
        $rules->add($rules->existsIn(['district_id'], 'Districts'));

        return $rules;
    }
}

src/Controller/SchoolsController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Schools Controller
 *
 * @property \App\Model\Table\SchoolsTable $Schools
 */
class SchoolsController extends AppController{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function adminIndex(){
        $this->paginate = [
            'contain' => ['Districts','Provinces','Regions']
        ];
        $schools = $this->paginate($this->Schools);
        
        $this->set(compact('schools'));
        $this->set('_serialize', ['schools']);
    }

    public function index(){
         $school = $this->Schools->newEntity();
         
         $this->set('school',$school);
         $this->set('_serialize',['school']);
    }

    public function findByRbd($rbd){
        $this->viewBuilder()->layout('ajax');
        $school = $this->Schools->find('all')
            ->where(['rbd' => $rbd])
            ->contain(['Provinces','Districts','Regions'])
            ->first()
            ->toArray();
        echo json_encode($school);
    }

}

src/Template/Schools/admin_index.ctp
<?php $this->assign('title', 'Admin FIE | Instituciones'); ?>
<section class="content-header">
    <h1 class="page-header"><?=__('Instituciones');?></h2>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i>
            <?=$this->Html->link(__('Dashboard'),['plugin' => 'Users', 'controller' => 'Users','action' => 'adminDashboard']);?>
        </li>
        <li class="active">
            <i class="fa fa-users"></i> <?=__('Instituciones');?>
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <?=$this->Flash->render();?>
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"><?=__('Listado Instituciones');?></h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <style type="text/css">
                                thead th { color: #3c8dbc; }
                            </style>
                            <table class="table table-bordered table-hover dataTable">
                                <thead>
                                    <th><?= __('RBD') ?></th>
                                    <th><?= __('Nombre') ?></th>
                                    <th><?= __('Comuna');?></th>
                                    <th><?= __('Provincia');?></th>
                                    <th><?= __('Región');?></th>
                                    <th class="actions text-center"><?= __('Acciones') ?></th>
                                </thead>
                                <tbody>
                                    <?php foreach ($schools as $school): ?>
                                    <tr>
                                        <td><?= $this->Number->format($school->rbd) ?></td>
                                        <td><?= h($school->name) ?></td>
                                        <td><?= $school->district->name ?></td>
                                        <td><?= $school->province->name ?></td>
                                        <td><?= $school->region->name ?></td>
                                        <td class="actions" style="text-align: center">
                                            <?= $this->Html->link('<i class="fa fa-edit" aria-hidden="true"></i>',
                                                        ['action' => 'adminEdit',$school->id],
                                                        ['escape' => false,'title' => 'Editar']);
                                            ?>
                                            <?= $this->Form->postLink('<i class="fa fa-trash" aria-hidden="true"></i>',
                                                        ['action' => 'adminDelete', $school->id],
                                                        ['escape' => false, 'title' => 'Eliminar',
                                                         'confirm' => __('Estás seguro de eliminar ID # {0}?', $school->id)]);
                                            ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <ul class="pagination">
                                <?= $this->Paginator->prev('< ' . __('Anterior')) ?>
                                <?= $this->Paginator->numbers() ?>
                                <?= $this->Paginator->next(__('Siguiente') . ' >') ?>
                            </ul>
                            <p><?= $this->Paginator->counter() ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/Template/Schools/index.ctp
<?=$this->Html->script('/plugins/jQuery/jquery-2.2.3.min.js'); # jQuery 2.2.3 ?>

<?=$this->Form->create($school,[
    'novalidate' => false,
    'style' => 'width: 50%;'
]);?>
    <?=$this->Form->input('rbd',[
        'label' => 'Ingrese RBD:',
        'id' => 'SchoolRBD',
        'div' => false
    ]);?>
    <?=$this->Form->button('Buscar:',[
        'class' => 'btnBuscar',
        'style' => 'width: 20%;'
    ]);?>
    <?=$this->Form->input('name');?>
    <?=$this->Form->input('dependence');?>
    <?=$this->Form->input('geographical_area');?>
    <?=$this->Form->input('region_id',[
        'type' => 'text'
    ]);?>
    <?=$this->Form->input('province_id',[
        'type' => 'text'
    ]);?>
    <?=$this->Form->input('district_id',[
        'type' => 'text'
    ]);?>
<?=$this->Form->end();?>

<script type="text/javascript">
    $(document).ready(function(){
        $('.btnBuscar').click(function(e){
            e.preventDefault();
            var rbd = $('#SchoolRBD').val();
            $.ajax({
                url: '/schools/findByRbd/'+rbd,
                success: function(response){
                    var json_obj = JSON.parse(response);
                    $.each(json_obj,function(key,value){
                        switch(key){
                            case 'region':
                            case 'province':
                            case 'district':
                                $('input[name='+key+'_id]').val(value.name);
                                break;
                            default:
                                $('input[name='+key+']').val(value);
                                break;
                        }
                    });
                }
            });
        });
    });
</script>